import{a as p,S as d,i}from"./assets/vendor-CVWx-W0A.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const a of e)if(a.type==="childList")for(const c of a.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&r(c)}).observe(document,{childList:!0,subtree:!0});function o(e){const a={};return e.integrity&&(a.integrity=e.integrity),e.referrerPolicy&&(a.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?a.credentials="include":e.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function r(e){if(e.ep)return;e.ep=!0;const a=o(e);fetch(e.href,a)}})();const m="56320794-31c479758a0ddef69c373babb",y=p.create({baseURL:"https://pixabay.com/api/",timeout:1e4});async function g(t){const s={key:m,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:40};return(await y.get("/",{params:s})).data}let n=null;function h(){n||(n=new d(".gallery a",{captionsData:"alt",captionDelay:250}))}function L(t){const s=document.querySelector(".gallery");if(!s)return;const o=t.map(r=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${r.largeImageURL}">
        <img class="gallery-image" src="${r.webformatURL}" alt="${r.tags}" loading="lazy" />
      </a>
      <div class="gallery-info">
        <p class="gallery-stat"><span>Likes:</span> ${r.likes}</p>
        <p class="gallery-stat"><span>Views:</span> ${r.views}</p>
        <p class="gallery-stat"><span>Comments:</span> ${r.comments}</p>
        <p class="gallery-stat"><span>Downloads:</span> ${r.downloads}</p>
      </div>
    </li>`).join("");s.insertAdjacentHTML("beforeend",o),h(),n&&typeof n.refresh=="function"&&n.refresh()}function b(){const t=document.querySelector(".gallery");t&&(t.innerHTML="")}function v(){const t=document.querySelector(".loader");t&&t.classList.add("is-visible")}function u(){const t=document.querySelector(".loader");t&&t.classList.remove("is-visible")}const l=document.querySelector(".form"),f=l?l.querySelector('input[name="search-text"]'):null;l&&f&&l.addEventListener("submit",async t=>{t.preventDefault();const s=f.value.trim();if(!s){i.error({title:"Error",message:"Please enter a search term"});return}b(),v();try{const o=await g(s);u();const r=o.hits||[],e=o.totalHits||0;if(!r.length){i.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});return}L(r),i.success({title:"Success",message:`Found ${e} images.`})}catch(o){u(),i.error({title:"Error",message:o.message})}});
//# sourceMappingURL=index.js.map
